language: scala

scala:
  - 2.12.3

jdk:
  - oraclejdk8

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test
