name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'sbt'
      - uses: scalacenter/sbt-dependency-submission@v3
      - name: 👌 Run "pre-push" tasks (compile and style-check)
        run: sbt prep
      - name: ✅ Generate a project and run its test
        run: sbt g8Test
